---
- name: Adding group {{ user_name }}
  group:
    name: "{{ user_name }}"

- name: Adding user {{ user_name }}
  user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    create_home: yes
    ssh_key_comment: "{{ user_name }}"

- name: Fetch public key file from machine
  fetch:
    src: /home/{{ user_name }}/.ssh/id_rsa.pub
    dest: "{{ keys_directory }}/{{ user_name }}_id_rsa.pub"
    flat: yes

- name: Fetch private key file from machine
  fetch:
    src: /home/{{ user_name }}/.ssh/id_rsa
    dest: "{{ keys_directory }}/{{ user_name }}_id_rsa"
    flat: yes

- name: Add {{ user_name }} to /etc/sudoers.d/
  lineinfile:
    path: /etc/sudoers.d/{{ user_name }}
    line: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
    create: yes
  when: sudo_rights|bool
